name: lstMCpipe
channels:
  - default
  - cta-observatory
  - conda-forge
dependencies:
  - python=3.7
  - astropy~=4.2
  - pip
  - pre-commit
  - ctapipe~=0.10.5
  - pip:
      - ctaplot>=0.5
      - ctapipe_io_lst~=0.9.2
      - lstchain==0.7.3
      - pyirf~=0.4.0
